IgnorePaths is not defined
I just installed the latest version (0.7.0) and receive this error. It is because the IgnorePaths is declared after its usage. 

```
>>> from requestlogs import middleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/requestlogs/__init__.py", line 1, in <module>
    from .base import get_requestlog_entry
  File "/usr/local/lib/python3.9/site-packages/requestlogs/base.py", line 44, in <module>
    populate_settings(SETTINGS)
  File "/usr/local/lib/python3.9/site-packages/requestlogs/base.py", line 36, in populate_settings
    _settings['IGNORE_PATHS'] = IgnorePaths(ignore_paths)
NameError: name 'IgnorePaths' is not defined
```